# Prometheus configuration for HFT Trading System monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'hft-trading'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load alerting rules
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # HFT Trading System metrics
  - job_name: 'hft-trading'
    static_configs:
      - targets: ['hft-trading:8080']
    scrape_interval: 5s  # High frequency for trading metrics
    scrape_timeout: 3s
    metrics_path: /metrics
    honor_labels: true
    
    # Relabeling for better organization
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: hft-trading:8080

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

# Remote write configuration for long-term storage
remote_write:
  - url: "https://monitoring.company.com/api/v1/write"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'hft_.*'
        action: keep

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 50GB
    wal-compression: true